task(#18): Библиотека программного кода и агент для её вызова
Kirill20poshliy/GlobexIT-Adaptation pull request #20
Opened 2024-07-24 10:37 UTC by Kirill20poshliy

2024-07-25 08:07 UTC, AlexeiStel commented on code_lib/src/agnt_call_lib/agnt_call_lib_method.ts
> +                if (!userId || !notificationTypeId)
if вынести перед  switch

2024-07-25 08:46 UTC, AlexeiStel approved these changes

2024-07-26 14:22 UTC, yavabit requested changes

2024-07-26 14:22 UTC, yavabit commented on code_lib/src/lib_collaborator/lib_collaborator.ts
должно быть описание методов библиотеки в формате jsdoc

2024-07-29 08:31 UTC, yavabit approved these changes

2024-07-29 08:49 UTC, merged